// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_3.Database
{
    public partial class DatChuyen
    {
        public int IDChuyen { get; set; }
        public int IDKhachHang { get; set; }
        public int? IDTongDaiVien { get; set; }
        public int? IDTaiXe { get; set; }
        public string DiemDon { get; set; }
        public DateTime? ThoiGianDon { get; set; }
        public string DiemKetThuc { get; set; }
        public int? Longitude { get; set; }
        public int? Latitude { get; set; }
        public DateTime? ThoiGianKetThuc { get; set; }
        public decimal? GiaTien { get; set; }
        public string TrangThai { get; set; }

        public virtual KhachHang IDKhachHangNavigation { get; set; }
        public virtual NhanVien IDTaiXeNavigation { get; set; }
        public virtual NhanVien IDTongDaiVienNavigation { get; set; }
    }
}