// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_3.Database
{
    public partial class NhanVien
    {
        public NhanVien()
        {
            DatChuyenIDTaiXeNavigations = new HashSet<DatChuyen>();
            DatChuyenIDTongDaiVienNavigations = new HashSet<DatChuyen>();
        }

        public int IDNhanVien { get; set; }
        public int? IDQuyen { get; set; }
        public int? IDChucVu { get; set; }
        public int? IDTaiKhoan { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string Image { get; set; }
        public int? Longitude { get; set; }
        public int? Latiude { get; set; }

        public virtual PhanQuyen IDQuyenNavigation { get; set; }
        public virtual TaiKhoan IDTaiKhoanNavigation { get; set; }
        public virtual ICollection<DatChuyen> DatChuyenIDTaiXeNavigations { get; set; }
        public virtual ICollection<DatChuyen> DatChuyenIDTongDaiVienNavigations { get; set; }
    }
}