// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_3.Database
{
    public partial class PhanQuyen
    {
        public PhanQuyen()
        {
            NhanViens = new HashSet<NhanVien>();
        }

        public int IDQuyen { get; set; }
        public int IDChucVu { get; set; }
        public string TenQuyen { get; set; }
        public string MoTa { get; set; }

        public virtual ChucVu IDChucVuNavigation { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}